#! /bin/sh

# clone-flexdll
#
# Brings in flexdll, if necessary

if [ -d "flexdll" ] && [ -f "flexdll/flexdll.c" ]; then
    echo "[Flexdll] Already present, no need to clone."
else
    echo "[Flexdll] Cloning..."
    git clone https://github.com/alainfrisch/flexdll
    cd flexdll
    git checkout 0.39
    cd ..
    echo "[Flexdll] Clone successful!"
fi
