#! /bin/bash

# esy-build
#
# Wrapper to execute appropriate build strategy, based on platform

set -u
set -e
set -o pipefail

case "$(uname -s)" in
    CYGWIN*|MINGW32*|MSYS*)
        echo "[esy-build] Detected windows environment..."
        make -j16 world.opt
        make flexlink.opt
        ;;
    *)
        echo "[esy-build] Detected OSX / Linux environment"
        make -j16 world.opt
        ;;
esac

# Common build steps
make install

patch () {

mv $cur__bin/$NAME $cur__bin/${NAME}_stock
cat >$cur__bin/$NAME <<EOF
#! /bin/sh

eval $cur__bin/${NAME}_stock -lto '"$@"'

EOF

}

patch ocamlopt.byte
patch ocamlopt.opt
