#! /bin/bash

set -u
set -e
set -o pipefail

./esy-configure \
  -target $ESY_CROSS_COMPILER_TARGET \
  -host $ESY_CROSS_COMPILER_HOST \
  -prefix $cur__install \
  -flambda \
  -no-debugger \
  -no-cfi \
  -cc "$ESY_CROSS_COMPILER_CC" \
  -aspp "$ESY_CROSS_COMPILER_CC -c"
make -j12 world.opt
make install